---
apiVersion: v1
kind: Service
metadata:
  name: hrpy-api
  namespace: kingdonb
  labels:
    app.kubernetes.io/instance: pzaexcp
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: hrpy-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: pzaexcp
    app.kubernetes.io/name: hrpy-api
    app.kubernetes.io/part-of: pzaexcp
    app.kubernetes.io/version: v1
  name: hrpy-api
  namespace: kingdonb
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrpy-api
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/trace-collector: oc-collector.tracing:55678
      labels:
        app: hrpy-api
    spec:
      containers:
      - command: ["bash"]
        args: ["--login", "-c", "yarn install && rails s -e development -p 3000 -b\
            \ 0.0.0.0"]
        env:
        - name: RAILS_ENV
          value: development
        - name: RAILS_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: hrpy-api-secret
              key: rails-secret-key-base
        - name: TNS_ADMIN
          valueFrom:
            secretKeyRef:
              name: hrpy-api-secret
              key: tns-admin
        - name: WEBSVC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: hrpy-api-secret
              key: websvc-db-username
        - name: WEBSVC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hrpy-api-secret
              key: websvc-db-password
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: hrpy-api-secret
              key: db-url
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: hrpy-api-secret
              key: smtp-host
        - name: THREESCALE_SERVICE_ID
          valueFrom:
            secretKeyRef:
              name: hrpy-api-secret
              key: threescale-service-id
        - name: THREESCALE_PROVIDER_KEY
          valueFrom:
            secretKeyRef:
              name: hrpy-api-secret
              key: threescale-provider-key
        imagePullPolicy: IfNotPresent
        image: kingdonb/hrpy-api:okteto-dev-8f3f8a4f
        name: hrpy-api
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: person-api
  namespace: kingdonb
  labels:
    app.kubernetes.io/instance: pzaexcp
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: person-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: pzaexcp
    app.kubernetes.io/name: person-api
    app.kubernetes.io/part-of: pzaexcp
    app.kubernetes.io/version: v1
  name: person-api
  namespace: kingdonb
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-api
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/trace-collector: oc-collector.tracing:55678
      labels:
        app: person-api
    spec:
      containers:
      - command: ["bash"]
        args: ["--login", "-c", "yarn install && rails s -e development -p 3000 -b\
            \ 0.0.0.0"]
        env:
        - name: RAILS_ENV
          value: development
        - name: RAILS_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: person-api-secret
              key: rails-secret-key-base
        - name: TNS_ADMIN
          valueFrom:
            secretKeyRef:
              name: person-api-secret
              key: tns-admin
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: person-api-secret
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: person-api-secret
              key: db-password
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: person-api-secret
              key: db-url
        - name: THREESCALE_SERVICE_ID
          valueFrom:
            secretKeyRef:
              name: person-api-secret
              key: threescale-service-id
        - name: THREESCALE_PROVIDER_KEY
          valueFrom:
            secretKeyRef:
              name: person-api-secret
              key: threescale-provider-key
        imagePullPolicy: IfNotPresent
        image: kingdonb/person-api:okteto-dev-827689e2
        name: person-api
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: pzaexcp-api
  namespace: kingdonb
  labels:
    app.kubernetes.io/instance: pzaexcp
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: pzaexcp-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: pzaexcp
    app.kubernetes.io/name: pzaexcp-api
    app.kubernetes.io/part-of: pzaexcp
    app.kubernetes.io/version: v1
  name: pzaexcp-api
  namespace: kingdonb
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pzaexcp-api
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/trace-collector: oc-collector.tracing:55678
      labels:
        app: pzaexcp-api
    spec:
      containers:
      - command: ["bash"]
        args: ["--login", "-c", "yarn install && rails s -e development -p 3000 -b\
            \ 0.0.0.0"]
        env:
        - name: RAILS_ENV
          value: development
        - name: TNS_ADMIN
          valueFrom:
            secretKeyRef:
              name: pzaexcp-api-secret
              key: tns-admin
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: pzaexcp-api-secret
              key: database-url
        - name: DATABASE_TEST_URL
          valueFrom:
            secretKeyRef:
              name: pzaexcp-api-secret
              key: database-test-url
        - name: PERSON_API_BASE
          valueFrom:
            secretKeyRef:
              name: pzaexcp-api-secret
              key: person-api-base
        - name: PERSON_API_KEY
          valueFrom:
            secretKeyRef:
              name: pzaexcp-api-secret
              key: person-api-key
        - name: THREESCALE_SERVICE_ID
          valueFrom:
            secretKeyRef:
              name: pzaexcp-api-secret
              key: threescale-service-id
        - name: THREESCALE_SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: pzaexcp-api-secret
              key: threescale-service-token
        imagePullPolicy: IfNotPresent
        image: kingdonb/pzaexcp-api:api-okteto-dev-4631253e
        name: pzaexcp-api
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: pzaexcp-frontend
  namespace: kingdonb
  labels:
    app.kubernetes.io/instance: pzaexcp
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: pzaexcp-frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: pzaexcp
    app.kubernetes.io/name: pzaexcp-frontend
    app.kubernetes.io/part-of: pzaexcp
    app.kubernetes.io/version: v1
  name: pzaexcp-frontend
  namespace: kingdonb
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pzaexcp-frontend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/trace-collector: oc-collector.tracing:55678
      labels:
        app: pzaexcp-frontend
    spec:
      containers:
      - command: ["bash"]
        args: ["--login", "-c", "yarn install && rails s -e development -p 3000 -b\
            \ 0.0.0.0"]
        env:
        - name: RAILS_ENV
          value: development
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: OC_AGENT_HOST
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: oc-agent-host
        - name: FORM_API_BASE
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: form-api-base
        - name: HRPY_API_BASE
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: hrpy-api-base
        - name: PERSON_API_BASE
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: person-api-base
        - name: BANNER_ADMIN_URL_BASE
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: banner-admin-url-base
        - name: HRPY_API_KEY
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: hrpy-api-key
        - name: PERSON_API_KEY
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: person-api-key
        - name: FORM_API_KEY
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: form-api-key
        - name: OKTA_REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: okta-redirect-uri
        - name: OKTA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: okta-client-id
        - name: OKTA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: okta-client-secret
        - name: OKTA_SITE
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: okta-site
        - name: OKTA_AUTH_SERVER_ID
          valueFrom:
            secretKeyRef:
              name: pzaexcp-frontend-secret
              key: okta-auth-server-id
        imagePullPolicy: IfNotPresent
        image: kingdonb/pzaexcp-frontend:frontend-okteto-dev-c3813bc3
        name: pzaexcp-frontend
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: finance-api
  namespace: kingdonb
  labels:
    app.kubernetes.io/instance: pzaexcp
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: finance-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: pzaexcp
    app.kubernetes.io/name: finance-api
    app.kubernetes.io/part-of: pzaexcp
    app.kubernetes.io/version: v1
  name: finance-api
  namespace: kingdonb
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-api
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/trace-collector: oc-collector.tracing:55678
      labels:
        app: finance-api
    spec:
      containers:
      - command: ["bash"]
        args: ["--login", "-c", "yarn install && rails s -e development -p 3000 -b\
            \ 0.0.0.0"]
        env:
        - name: RAILS_ENV
          value: development
        - name: RAILS_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: finance-api-secret
              key: rails-secret-key-base
        - name: TNS_ADMIN
          valueFrom:
            secretKeyRef:
              name: finance-api-secret
              key: tns-admin
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: finance-api-secret
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finance-api-secret
              key: db-password
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: finance-api-secret
              key: db-url
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: finance-api-secret
              key: smtp-host
        - name: THREESCALE_SERVICE_ID
          valueFrom:
            secretKeyRef:
              name: finance-api-secret
              key: threescale-service-id
        - name: THREESCALE_PROVIDER_KEY
          valueFrom:
            secretKeyRef:
              name: finance-api-secret
              key: threescale-provider-key
        imagePullPolicy: IfNotPresent
        image: kingdonb/finance-api:api-dev-e7544b5d
        name: finance-api
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: 100m
